const:
  jwt:
    issuer: green@green.kr #?? ???
    secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
    header-schema-name: Authorization
    token-type: Bearer
    access-token-expiry: 600_000 #10?
    refresh-token-expiry: 1_296_000_000 #15?
    refresh-token-cookie-name: refresh-token

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    username: root
    password: green502

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true